-- 코드를 입력하세요
SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE A
WHERE A.SALES_DATE >= '2022-03-01' AND A.SALES_DATE < '2022-04-01'
UNION ALL
SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE B
WHERE B.SALES_DATE >= '2022-03-01' AND B.SALES_DATE < '2022-04-01'

ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC